commands:
  list: true
  vanish: true
  nickname: true
  nickreset: true
  color: true
  realname: true
  rename: true
features:
  update-check: true
  join-leave: true
  motd: true
  qol: true
  sleeping: true
  nickname-length: 32
  chat-formatting: true
  debug: false
Version: 1.6
