commands:
    list: true
    vanish: true
    nickname: true
    nickreset: true
    color: true
    realname: true
    rename: true
features:
    update-check: true
    motd: true
    qol: true
    sleeping: true
    chat-formatting: true
Version: 1.3